ais_dosens:
    type: rest
    prefix: /api
    resource: "@AisDosenBundle/Resources/config/routes.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
